### ISSUE TITLE
How do I get react to load?

### ISSUE THREAD

**Issue by ralyodio** [router5/react-router5#12]
I'm using babel to build everything but when I load the page I get `Uncaught ReferenceError: require is not defined`

**Comment by troch** [comment]
That is because you need a CommonJS module implementation, usually provided by a module bundler like browserify or webpack.

**Comment by ralyodio** [comment]
I'm just trying to run the react example. Can you put up instructions on how to run this app properly?

**Comment by troch** [comment]
It is not an app, they are just code snippets demonstrating how to bind router5 with react. I have a repo with example apps: https://github.com/router5/examples with instructions on how to build and run.

**Comment by troch** [comment]
Examples use webpack, you can also use browserify. Alternatively, it has a "browser" distribution (look in `dist` folder or install with bower) and exposes a global object `router5React` with `Link`, `RouterProvider` and `routeNode`.

**Comment by ralyodio** [comment]
For anyone curious here's how I got it to work:

```
var browserify = require('browserify');
var babelify = require('babelify');
var source = require('vinyl-source-stream');

gulp.task('build:client:react', function(){
  return browserify({entries: 'client/app.js', extensions: ['.js'], debug: true})
    .transform(babelify)
    .bundle()
    .pipe(source('bundle.js'))
    .pipe(gulp.dest('dist/client/'));
});
```
