### ISSUE TITLE
route only loads page on refresh

### ISSUE THREAD

**Issue by ralyodio** [router5/react-router5#13]
I see the route is changing in the address bar, but my page content does not change unless I refresh the page.

I'm trying to make the react5-example work, but the routing is a little different than the example.

I want `/#/games` to load a list of games and when I click a game it goes to `/#/games/view/<id>`

this works...but not when i click the links...it does not load the content unless I fully refresh the page in the browser.

I'm missing something, not sure what though.

Here are my routes:

```
  // Routes
  .addNode('games', '/games')
  .addNode('games.view', '/view/:id')
```

and on each component I have:

```
export default routeNode('games')(Games);
```

and

```
export default routeNode('games.view')(Game);

```

I'm following links two different ways. One with an anchor tag and onClick that prevents default.

```
        <h4><a href='#' onClick={ this.clickHandler }>{ title }</a></h4>
...
  clickHandler(e) {
    e.preventDefault();
    this.router.navigate('games.view', {id: this.props.id});
  }
```

The other I'm using `<Link>` component but neither are loading the page.

```
        <Link routeName='games' className="item">
          <i className="block layout icon"></i>
          Games
        </Link>
```

**Comment by troch** [comment]
So it is important to understand what `routeNode` does. It does not map a route to a component, it maps a routeNode to a component. `routeNode` is a higher-order component which will create a new component from the base component you provide, and will re-render your base component (providing it with route name and params) when it needs to.

A `routeNode` higher-order component registers a routeNode listener with the router. To understand exactly what it is and when it would be invoked, look at this documentation: http://router5.github.io/docs/listeners.html

**Comment by ralyodio** [comment]
@troch thanks. So if I understand this correctly, my route.js file needs a route handler for each route?

```

myRouter.addRouteListener('games', function (toState, fromState) {
    alert('You have navigated to games');
   //how do i call the games component?
});
```

**Comment by troch** [comment]
You shouldn't need route listeners. Only node listeners. Route listeners comes handy for updating non main parts of your screen.

Look here: https://github.com/router5/examples/blob/master/apps/react/components/Main.js

**Comment by ralyodio** [comment]
I have that already and it just doesn't do anything unless I refresh the page.

```
import React, { createElement } from 'react';
import { routeNode } from 'react-router5';
import Games from './games';
import Game from './Game';
import NotFound from './NotFound';

const components = {
  'games':   Games,
  'games.view': Game
};

function Main(props) {
  const { route } = props;
  const segment = route.name;

  return createElement(components[segment] || NotFound);
}

export default routeNode('')(Main);
```

**Comment by troch** [comment]
You cannot place `games` and `games.view` on the same node, according to your route definition they are descendants. If you go from `games` to `games.view`, root node (`routeNode('')`)  won't re-render, but `games` node will.

You can use https://github.com/router5/helpers.

If you don't intend the following (nested components), then don't nest your routes!

``` javascript
import { startsWithSegment }  from 'router5.helpers';

const rootNode = rootNode('')(Main);

function Main(props) {
  const { route } = props;
  const segment = route.name;

  if (startsWithSegment(segment, 'games')) return <Games />
  else return NotFound;
}

export default routeNode('')(Main);
```

And in your games file (pseudo code)

```
function Games() {
   return (
      <div>
              /* Your logic here */
             { routeIsGameView ? <Game id={ ... } /> : null } 
      </div>
}

export default route routeNode('games')(Games);
```

There are many ways you can proceed. It all depends what you want to do, I know this can be intimidated. For instance, instead of making Games your `games` Node, you can create a new component wrapping `Game` and taking responsibility for re-rendering the `games` node (useful if your `Games` component contains some content which will always be present whether or not you are in `games` or `games.view`).

**Comment by ralyodio** [comment]
I guess i'm at a bit of a loss with all the terminology. I looked at react-router and it seems straight forward. I just want two pages that load two different components.

**Comment by troch** [comment]
If your case is straight forward and you are fairly new to React, react-router is a good shout. I know the docs can be improved, but what is it that you don't understand in the terminology?

**Comment by ralyodio** [comment]
I guess I'm unclear what the example is doing with router5-react

The react-router page has a detailed getting started example that walks you through setting up the different types of routes. I didn't find anything like that with router5.
