### ISSUE TITLE
home link in example doesn't work

### ISSUE THREAD

**Issue by ralyodio** [router5/react-router5#14]
```
SideBar.js
        <Link routeName='' className="item">
          <i className="home icon"></i>
          Home
        </Link>
```

```
Main.js
export default routeNode('')(Main);
```

```
router.js

const router = new Router5()
  .setOption('useHash', true)
  // .setOption('hashPrefix', '!')
  .setOption('defaultRoute', 'games')
  // Routes
  .addNode('games', '/games')
  .addNode('game', '/games/:id')
  // Plugins
  .usePlugin(Router5.loggerPlugin())
  .usePlugin(listenersPlugin())
  .usePlugin(historyPlugin());

```

When I load the page the first time it redirects the homepage to `/#/games` but when I click the SideBar link to `Home` it does nothing and I get a warning: `Transition error with code ROUTE_NOT_FOUND`

When I to click Home from the `/#/games/:id` page

**Comment by troch** [comment]
You need to define a home route in your routes. The "unamed" node is not a route you can activate. If you imagine your routes in a tree, it is just the node at the top, but is not a route you defined and therefore not a route which really exists.

**Comment by ralyodio** [comment]
Ok, so I need to make the `<Link>` element use the defaultRoute value? In this case `games`

**Comment by troch** [comment]
You need to explicitly pass a route to Link, yes

**Comment by troch** [comment]
I have published a new page in the docs which should help you understand more of how things work together: http://router5.github.io/docs/understanding-router5.html
