### ISSUE TITLE
Importing segmentMixinFactory breaks React Developer Tools

### ISSUE THREAD

**Issue by CrshOverride** [router5/react-router5#2]
I'm currently working on implementing a very simple example of using `Router5` with React. Following the documentation, I created a `router.js` file as follows:

``` javascript
import {Router5} from 'router5';

let router =
    new Router5()
        .setOption('useHash', false)
        .addNode('search', '/')
        .addNode('search.results', ':q')
        .start();

export {router};
```

When loading the application, the React Developer Tools show me exactly what I'm expecting to see with my simple app:

<img width="404" alt="screenshot 2015-08-17 18 17 30" src="https://cloud.githubusercontent.com/assets/791698/9317924/d27987ee-450c-11e5-9f5d-ae1b38187d2c.png">

When I add `segmentMixinFactory` as follows:

``` javascript
import {Router5} from 'router5';
import {segmentMixinFactory} from 'router5-react';

let router =
    new Router5()
        .setOption('useHash', false)
        .addNode('search', '/')
        .addNode('search.results', ':q')
        .start();

let SegmentMixin = segmentMixinFactory(router);

export {router, SegmentMixin};
```

The React Developer Tools show absolutely no elements:

<img width="183" alt="screenshot 2015-08-17 18 17 15" src="https://cloud.githubusercontent.com/assets/791698/9317957/12f85264-450d-11e5-833e-049d8d2ae0dd.png">

**Comment by troch** [comment]
Hi Justin,

I can see two potential issues in your code:
- `let router5 = undefined;`
- You possibly need to add `default` to your exports: `export default {router}`, `export default {router, SegmentMixin};`

If it is not the issue, can you share more of your code?

Thanks

**Comment by CrshOverride** [comment]
Sorry about that @troch. Those were actually typos in my example. I've updated my original issue to remove the sets to `undefined` as those were added for some debugging. Adding `default` to the `export` also didn't make any change.

I also forgot to mention that I'm using the ES6 class syntax rather than `React.createClass`. After a cursory glance at how to get mixins working with that structure (basically, it sounds like they don't work) I created a `SegmentComponent` base class that implemented the same functionality as the mixin returned from `segmentMixinFactory`.

That got me passed that issue but I still couldn't quite get routing working properly. Since I only had a couple of days to hack on the project, I went with a different routing library.

If you're interested, I'll gladly switch back and see if I can get a `SegmentComponent` working properly and create a PR?

**Comment by troch** [comment]
You are right, Mixins don't work with ES6 syntax. You can extend a class `SegmentComponent` but I think we could use decorators (which might be more elegant). If you want to submit a PR, no problem :+1:

**Comment by CrshOverride** [comment]
@troch I was on the fence about decorators since they're an ES7 feature rather than ES6. I can always give that a shot as well.

**Comment by troch** [comment]
@CrshOverride do what you are more comfortable with. I'm in favour of having the two available, so ppl can use whatever they are used to: mixin, base class or decorator. If you do the base class, I'll add the decorator.

**Comment by troch** [comment]
Repo renamed to react-router5, router5@1.0.0 released. No more mixin and use of higher-order components instead.
