### ISSUE TITLE
npm image is broken

### ISSUE THREAD

**Issue by bebraw** [router5/react-router5#20]
The image at the [npm page](https://www.npmjs.com/package/react-router5) is broken. You could try pointing through [rawgit](https://rawgit.com/) instead. Here's a link that should work: https://cdn.rawgit.com/router5/router5.github.io/master/img/router-view.png .

**Comment by troch** [comment]
I've just updated the README file according to your suggestion, but it won't be updated until released (on npm).

How stable is rawgit? I had a look at their twitter account, looks like they are still at an early stage with their project.

**Comment by bebraw** [comment]
I'm not sure. That was the first idea that popped to my mind.

If you have a stable third party in mind, that would work as well.

**Comment by troch** [comment]
I could change it to: https://raw.githubusercontent.com/router5/router5.github.io/master/img/router-view.png

**Comment by bebraw** [comment]
Note that GitHub's headers are broken. That's why RawGit exists. But still worth a go perhaps.

**Comment by troch** [comment]
New release fixed it I believe :)

**Comment by bebraw** [comment]
Looks good. 👍
