### ISSUE TITLE
Link produces absolute URL

### ISSUE THREAD

**Issue by vojtech-dobes** [router5/react-router5#21]
Hi, is it correct observation that `Link` component now produces absolute URLs? So far we've highlighted all external URLs in our app based on assumption that they are absolute (internal URLs were relative) and now after upgrade to 4.0.0 _all_ our in-app URLs are highlighted as external :).

**Comment by troch** [comment]
Hmm no that shouldn't be, nothing has changed in the way URLs are generated. Are you setting a base option? are you using `useHash: true`?

The function generating the URL is here: https://github.com/router5/router5/blob/master/modules/plugins/browser/utils.js#L6-L10
`options.base` is guessed if `useHash` is set to true and if you don't supply a `base` option:
https://github.com/router5/router5/blob/master/modules/plugins/browser/browser.js#L17

**Comment by vojtech-dobes** [comment]
We don't use `useHash`. We supply `base` - according to Migration guide we newly pass it to `browserPlugin`:

``` diff
-var router = new Router5([], {
+var router = createRouter([], {
-   base: `${location.protocol}//${location.host}`,
    trailingSlash: true,
});
-router.usePlugin(historyPlugin());
+router.usePlugin(browserPlugin({
+   base: `${location.protocol}//${location.host}`,
+}));
```

**Comment by troch** [comment]
I'm surprised you didn't experience issues before. The `base` option is the part you want to keep from your `location.pathname` (otherwise the router overwrites everything after `location.host`), my next job is to make the docs much better.

Not supplying a base in your case will work :)

**Comment by vojtech-dobes** [comment]
> Not supplying a base in your case will work :)

Thanks, will try :).
