### ISSUE TITLE
Question: how to go back to the previous state

### ISSUE THREAD

**Issue by ajmeyghani** [router5/react-router5#25]
Thanks for the great library. I was wondering if there is a react/router5 way of going back to the previous state. Right now I'm using `window.history.back();`. It works but I have a feeling that's not the right way of doing it if I'm using react and react-router5.

Thanks in advance!

**Comment by troch** [comment]
Sorry for the late reply. `history.back()` is the best option in browser.

Another solution is to have your own plugin keeping track of successive states, and adding a `back` method on router instances: but what it will do is adding a new state, therefore a new history entry... which makes `history.back` better.

**Comment by ajmeyghani** [comment]
Awesome, thank you!
