### ISSUE TITLE
allowNotFound support

### ISSUE THREAD

**Issue by prashaantt** [router5/react-router5#26]
Does this lib support the `allowNotFound` option yet? I have `allowNotFound` set but clicking on an arbitrary link like `<Link routeName="unknown">Unknown</Link>` does not change the router state, even with ROUTE_NOT_FOUND error.

**Comment by troch** [comment]
`<Link routeName="unknown">Unknown</Link>` cannot work, the router doesn't know how to translate that route name to a path. Is what you need instead a simple `<a href='/unkown'>Unknown</a>`?

**Comment by prashaantt** [comment]
All right, I'm coming from react-router that has a different behaviour.

I tried `<a href='/unkown'>Unknown</a>` — is there a way to avoid a full page refresh when doing that?

**Comment by troch** [comment]
Yeah, a simple link would reload. `allowNotFound` is designed to be used on start (page load in the browser, request on server-side), to allow the router to emit a state for any URL. I don't see why you would need a `Link` pointing to a route you know doesn't exist. Could you give me more details, to help me understand?

**Comment by prashaantt** [comment]
No specific use case, I was just trying out this hypothetical scenario where a Link for an undefined route may be dynamically generated.

**Comment by troch** [comment]
If you are ever in that case, just let me know.

**Comment by prashaantt** [comment]
Sure, thanks!
