### ISSUE TITLE
Invalid prop `children` of type `array` supplied to `RouterProvider`, expected a single ReactElement.

### ISSUE THREAD

**Issue by iyobo** [router5/react-router5#28]
Invalid prop `children` of type `array` supplied to `RouterProvider`, expected a single ReactElement.
    in RouterProvider
printWarning @ warning.js:36
warning @ warning.js:60
checkReactTypeSpec @ checkReactTypeSpec.js:80
validatePropTypes @ ReactElementValidator.js:151
createElement @ ReactElementValidator.js:194
(anonymous) @ adminApp.jsx:38
__webpack_require__ @ bootstrap ff33905…:19
(anonymous) @ bootstrap ff33905…:39
(anonymous) @ bootstrap ff33905…:39

**Comment by troch** [comment]
Hi
