### ISSUE TITLE
Click on <Link> always causes reload

### ISSUE THREAD

**Issue by vojtech-dobes** [router5/react-router5#3]
I was able to find that `evt.nativeEvent.which` in [`link-factory`](https://github.com/router5/router5-react/blob/6092808ecc12d215114f26ffe2744d265fc05fb4/modules/link-factory.js#L43) is `1`. Observed in Chrome 44.0.2403.157 and Safari 8.0.8. No idea what causes, what it means, but it prevents the `clickHandler` from doing its job :).

**Comment by vojtech-dobes** [comment]
What is purpose of that condition? If I get it correctly, `react-router` uses [following logic](https://github.com/rackt/react-router/blob/50ceba2671f6f05f95c9d7a5e95ba375a4a4d52c/modules/components/Link.js#L5-L11) to [filter out](https://github.com/rackt/react-router/blob/50ceba2671f6f05f95c9d7a5e95ba375a4a4d52c/modules/components/Link.js#L40-L41) special clicks:

``` js
function isLeftClickEvent(event) {
  return event.button === 0;
}

function isModifiedEvent(event) {
  return !!(event.metaKey || event.altKey || event.ctrlKey || event.shiftKey);
}
```

**Comment by troch** [comment]
Hi @vojtech-dobes: the purpose of this condition is to not prevent default on middle click (so it opens a new tab using the hyperlink href). It works fine for me (click and enter key press do what is intended), I'll run more checks and test RR's logic :smile:

**Comment by vojtech-dobes** [comment]
Thanks for quick reply :). Great.

**Comment by troch** [comment]
Just released v0.1.4 using RR's logic :D

**Comment by vojtech-dobes** [comment]
Awesome sir :).

**Comment by troch** [comment]
Please tell me if you have any issue with it!

**Comment by vojtech-dobes** [comment]
Nope, works like a charm. No reloads, History API is in action now.

**Comment by troch** [comment]
:+1:
