### ISSUE TITLE
withRoute seems to require listenersPlugin

### ISSUE THREAD

**Issue by ezzatron** [router5/react-router5#30]
I'm using `react-router5`, and `redux-router5` (with the plugin, not the middleware).

I have a React component that I use to integrate with [Grommet](https://grommet.github.io/) (a React UI library). Grommet supplies its own styled [Anchor](https://grommet.github.io/docs/anchor) component, which I want to use in place of the `Link` component supplied by `react-router5`.

I managed to create this component, which works fine:

```js
import React from 'react'
import {withRoute} from 'react-router5'

import GrommetAnchor from 'grommet/components/Anchor'

export function Anchor (props) {
  const {label, routeName, routeParams, onClick: userOnClick, children, router} = props
  const href = router.buildPath(routeName, routeParams)

  function onClick (...args) {
    if (userOnClick) return userOnClick(...args)

    const [event] = args

    event.preventDefault()
    router.navigate(routeName, routeParams)
  }

  return <GrommetAnchor href={href} onClick={onClick} label={label}>{children}</GrommetAnchor>
}

export default withRoute(Anchor)
```

The problem is, as soon as I use this component, I get the following error message in the console:

```
utils.js:11 Uncaught Error: [react-router5][withRoute] missing listeners plugin
    at ifNot (utils.js:11)
    at ComponentWithRoute.componentDidMount (withRoute.js:48)
    at ReactCompositeComponent.js:265
    at measureLifeCyclePerf (ReactCompositeComponent.js:75)
    at ReactCompositeComponent.js:264
    at CallbackQueue.notifyAll (CallbackQueue.js:76)
    at ReactReconcileTransaction.close (ReactReconcileTransaction.js:80)
    at ReactReconcileTransaction.closeAll (Transaction.js:206)
    at ReactReconcileTransaction.perform (Transaction.js:153)
    at batchedMountComponentIntoNode (ReactMount.js:126)
```

Sure enough, if I add the listeners plugin, the problem goes away. But as far as I can tell, I shouldn't actually need the listeners plugin, according to the docs.

Any ideas? I'll post a link to an example app once I've submitted this issue.

EDIT: Example code available [here](https://github.com/darianbr/dballs-react-redux/tree/react-router5-issue-30)

**Comment by troch** [comment]
Hi @ezzatron,

Yes, `withRoute` requires the listener plugin. If you are using redux, you don't need the listeners plugin and therefore not `withRoute`. You just need `connect` with a selector to the current route `(state) => state.router.route`. To have your router instance in `props`, you need to grab it from context.

**Comment by ezzatron** [comment]
Ah, okay. I'm only using `router`, which I assumed came from `withRoute`, similar to `withRouter` that ships with `react-router`. Thanks!
