### ISSUE TITLE
React 15 ~ vs ^

### ISSUE THREAD

**Issue by klimashkin** [router5/react-router5#35]
Why did you [replace](https://github.com/router5/react-router5/commit/b54e8743bf589c1b2a50bb2bf007dd995922efa7#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L66) caret with tilde in peerDependencies?

Now npm warns me with latest React 15.5.4

**Comment by klimashkin** [comment]
`prop-types` also should have caret like [other](https://github.com/cloudflare/react-gateway/blob/master/package.json#L25) [libraries](https://github.com/cloudflare/react-gateway/blob/master/package.json#L25) [do](https://github.com/facebook/react/blob/master/packages/react/package.json#L29). 

To take library's consumer version, and avoid embedding two versions of `prop-types` into bundle by webpack when minor version will be released.

**Comment by troch** [comment]
Sorry, my mistake

**Comment by troch** [comment]
`4.2.1` out.
