### ISSUE TITLE
"// Is it overkill?" How to make <Link> re-render when children change?

### ISSUE THREAD

**Issue by vojtech-dobes** [router5/react-router5#6]
If I understand the code correctly, custom `shouldComponentUpdate` prevents re-render when only children change. How to solve this?

**Comment by troch** [comment]
`shouldComponentUpdate` could be removed, I think for a small component like tat, re-rendering a single virtual DOM element for nothing is not that expensive.

**Comment by troch** [comment]
Removed and 0.1.5 released

**Comment by vojtech-dobes** [comment]
Thanks!
