### ISSUE TITLE
More fine-grained detection of activeness

### ISSUE THREAD

**Issue by vojtech-dobes** [router5/react-router5#8]
Let's consider example:
- I am on route `foo` with query parameter `?bar=1`.
- I have link:

```
<Link routeName="foo">
</Link>
```

I don't use strict comparison, so I expected this link would be marked as active because `/foo` and `/foo?bar=1` seem to me pretty much same. Unfortunately there is no support for such low level distinction. Would you consider adding support for this (basically stripping query parameters from current route unless they are part of link's route)?

**Comment by troch** [comment]
This is a good suggestion. I'll add an option to .isActive to include or not query params (default to false).

**Comment by vojtech-dobes** [comment]
:+1:

**Comment by troch** [comment]
Released with router5@0.9.0
